name: Rust Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      name: Install rust toolchain
      with:
        toolchain: nightly
        override: true

    - uses: Swatinem/rust-cache@v2
      name: Add caching

    - uses: actions-rs/cargo@v1
      name: Build crate
      with:
        command: build
        args: --verbose

